### PR TITLE
refs ST-5091[*]: new format for sampling

### PR DESCRIPTION
**Pull request by ASenart**

### CODE REVIEW

**Comment by trungkienbkhn** [comment]
@ASenart , have you created a new systran/pn9_tf image to test the update logic in this PR? We need to check whether the model training workflow is affected or not.

**Comment by ASenart** [comment]
Yes I have a beta image working with this logic

**Comment by trungkienbkhn** [comment]
Could you push this image to the systran docker hub (or create new tag in systran-docker) ? I will also check it on my side.

**Comment by ASenart** [comment]
Here it is :  systran/pn9_tf:v1.81.8-SamplerFormat

**Comment by trungkienbkhn** [comment]
It's compatible with CM2 8.31.2-1.el8, right ?

**Comment by ASenart** [comment]
Yes it should be

**Comment by trungkienbkhn** [comment]
I encountered the error below when running prepr task:
```
2024-May-24 10:49:07.056000 UTC [generic@MainProcess] INFO Downloading en_fr/train/ENFR_unibet_2_EN_01-FR_01 to /root/workspace/shared/corpus_shared_train_data/en_fr/train/ENFR_unibet_2_EN_01-FR_01
2024-May-24 10:49:07.060000 UTC [generic@MainProcess] INFO Downloading en_fr/train/testing_upload.txt to /root/workspace/shared/corpus_shared_train_data/en_fr/train/testing_upload.txt
2024-May-24 10:49:07.068000 UTC [corpus@MainProcess] INFO Downloading metadata of en_fr/train/ENFR_unibet_2_EN_01-FR_01 to /root/workspace/shared/corpus_shared_train_data/en_fr/train/.ENFR_unibet_2_EN_01-FR_01.metadata
2024-May-24 10:49:07.071000 UTC [corpus@MainProcess] INFO Downloading metadata of en_fr/train/testing_upload.txt to /root/workspace/shared/corpus_shared_train_data/en_fr/train/.testing_upload.txt.metadata
2024-May-24 10:49:07.086000 UTC [generic@MainProcess] INFO Downloading en_fr/train/training_upload.txt to /root/workspace/shared/corpus_shared_train_data/en_fr/train/training_upload.txt
2024-May-24 10:49:07.097000 UTC [corpus@MainProcess] INFO Downloading metadata of en_fr/train/training_upload.txt to /root/workspace/shared/corpus_shared_train_data/en_fr/train/.training_upload.txt.metadata
2024-May-24 10:49:07.128000 UTC [generic@MainProcess] INFO Delete files that exist in local but not in remote storage: ['/root/workspace/shared/corpus_shared_train_data/en_fr/train/.ENFR_unibet_2_EN_01-FR_01.md5', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.annotated_enfr_tatoeba_extract.json.md5', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/training_upload.txt.json', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/hash_sentences.txt.json', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/ENFR_unibet_2_EN_01-FR_01.json', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.education_enfr.txt.metadata', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/annotated_enfr_tatoeba_extract.json.json', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.annotated_enfr_tatoeba_extract.json.metadata', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/testing_upload.txt.json', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.ENFR_unibet_2_EN_01-FR_01.metadata', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.testing_upload.txt.metadata', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.training_upload.txt.metadata', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.training_upload.txt.md5', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.education_enfr.txt.md5', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.testing_upload.txt.md5', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/education_enfr.txt.json', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.hash_sentences.txt.metadata', '/root/workspace/shared/corpus_shared_train_data/en_fr/train/.hash_sentences.txt.md5']
2024-May-24 10:49:07.129000 UTC [sampler@MainProcess] INFO Sampling 2000000 lines...
Traceback (most recent call last):
  File "/root/entrypoint.py", line 797, in <module>
    PN9TFFramework().run()
  File "/root/nmtwizard/utility.py", line 296, in run
    stats = self.exec_function(args)
  File "/root/nmtwizard/framework.py", line 705, in exec_function
    return self.preprocess_into_model(
  File "/root/nmtwizard/framework.py", line 1408, in preprocess_into_model
    data_dir, num_samples, distribution_summary, tokens_to_add = self._build_data(
  File "/root/nmtwizard/framework.py", line 1692, in _build_data
    ) = self._generate_training_data(config)
  File "/root/nmtwizard/framework.py", line 1723, in _generate_training_data
    return preprocessor.generate_preprocessed_data()
  File "/root/nmtwizard/preprocess/preprocess.py", line 315, in generate_preprocessed_data
    all_files, summary = sampler.sample(
  File "/root/nmtwizard/preprocess/sampler.py", line 270, in sample
    all_files, pattern_weights_sum, pattern_sizes = _discover_files(source_dir)
  File "/root/nmtwizard/preprocess/sampler.py", line 149, in _discover_files
    size = reader.count_lines()
  File "/root/nmtwizard/preprocess/sampler.py", line 443, in count_lines
    with open(self.metadata_path) as metadata_file:
FileNotFoundError: [Errno 2] No such file or directory: '/root/workspace/shared/global_corpus/SA/dataset_for_test/train/.training_upload.txt.metadata'
```
It is caused by this [logic](https://github.com/SYSTRAN/storages/blob/master/systran_storages/storages/generic.py#L166). In this case, metadata + md5 file of old json corpus still exists in the local path.
So to avoid this bug, should change to this [logic](https://github.com/SYSTRAN/storages/blob/master/systran_storages/storages/generic.py#L152) to:
```python
  if extra_path in allfiles:
      del allfiles[extra_path]
  checksum_file = self._get_checksum_file(path)
  if checksum_file is not None and checksum_file in allfiles:
      del allfiles[checksum_file]
  metadata_file = self._get_metadata_file(path)
  if metadata_file is not None and metadata_file in allfiles:
      del allfiles[metadata_file]
```
Could you verify this point? Tks.

**Comment by trungkienbkhn** [comment]
Another question, how can I set the worker number with a different value instead of 1 (default)? Is there a config for workers to use in the systran/pn9_tf image?

**Comment by ASenart** [comment]
You need to use the environment variable NB_CPU=4

**Comment by trungkienbkhn** [comment]
Could you push a new version of image systran/pn9_tf:v1.81.8-SamplerFormat to docker hub?

**Comment by trungkienbkhn** [comment]
Your image looks good to me. But I encountered an minor issue with pylint:
```
storages/systran_storages/storages/generic.py:8:0: C0411: standard import "from multiprocessing.dummy import Pool" should be placed before "import six" (wrong-import-order)
```
Could you fix this, then I will merge your PR. Tks.

**Pull request merged**
